try:
    raise Exception("test exp")
except Exception as e:
    print(e)